version: "3.8"

services:
  be-service:
    build:
      context: .
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - .:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
    depends_on:
      - mongo
    # Overwrite any env var defined in .env file (if required)
    # environment:
    #   - MONGO_HOST=mongodb://kerem:kerem@localhost/perf-analytics
    #   - DEBUG=express-mongoose-es6-rest-api:*
  
  mongo:
    image: "mongo:4.4"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

networks:
  db:

volumes:
  db:
