version: "3.8"

services:
  mongo:
    image: "mongo:4.4"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: perf-analytics
      MONGO_INITDB_ROOT_USERNAME: kerem
      MONGO_INITDB_ROOT_PASSWORD: kerem

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kerem
      ME_CONFIG_MONGODB_ADMINPASSWORD: kerem

volumes:
  db:
